### ISSUE TITLE
`tlx::BTree<...>::find()` method cannot compile: 

### ISSUE THREAD

**Issue by ziyi-yan** [wheatman/BP-Tree#7]
I wrote a test program to call `tlx::BTree<...>::find()` but it cannot compile. Here is the error message:

[bptree-find-errors.txt](https://github.com/user-attachments/files/17511692/bptree-find-errors.txt)

Here is code snippet in my test program:
```cpp
tlx::btree_map<uint64_t, uint64_t, std::less<uint64_t>,
               tlx::btree_default_traits<uint64_t, uint64_t>,
               std::allocator<uint64_t>, /*concurrent=*/true>
    tree;
auto it = tree.find(k);
ASSERT_NE(it, tree.end());
```

I followed [this document](https://docs.google.com/document/d/1GqQBpYTzSixPAQMfuK8pHyDVL7OjqDHb-Q0u406x894/edit?tab=t.0#heading=h.ypcwkiygbwwu) to use the code at branch `artifact_evaluation`.

**Comment by wheatman** [comment]
Sorry, that functions isn't expected to work and probable should have been removed.
Basically returning an iterator to a concurrent data structure is complicated so we use a functional map style instead.

One of these should hopefully solve your issue

```cpp
int main() {
  tlx::btree_map<uint64_t, uint64_t, std::less<uint64_t>,
                 tlx::btree_default_traits<uint64_t, uint64_t>,
                 std::allocator<uint64_t>, /*concurrent=*/true>
      tree;
  // check if the elemnt is in the map
  auto x = tree.exists(1);
  // get the value assoctaied with the key in the map, if it doesn't exist
  // returns the default constructable value
  auto y = tree.value(1);

  // apply the function to all elements with keys between 0 and 10
  tree.map_range(0, 10, [](auto key, auto val) {

  });

  // apply the function to the first 10 elements which have keys greater than  or equal to 10
  tree.map_range_length(0, 10, [](auto key, auto val) {

  });
  return x;
}
```

**Comment by ziyi-yan** [comment]
Thanks for your response!
